# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# This workflow will deploy Azure Resource Inventory using GitHub Actions and schedule a monthly run.

name: Deploy Azure Resource Inventory

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
    paths: 
      - 'bicep'
      - 'ps'
      - '.github/workflows/deploy.yml'
  
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  actions: read # Required if repo is private.
  contents: read # Required if repo is private.

env:
  AZURE_RESOURCE_GROUP: rg-uks-sandbox-ari-pmc
  AZURE_LOCATION: uksouth

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Azure Login
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: deployRg
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: deploy-ari-rg
          location: ${{ env.AZURE_LOCATION }}
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: ./bicep/rg.bicep
          parameters: '{"rgName": ${{ env.AZURE_RESOURCE_GROUP }}, "location": ${{ env.AZURE_LOCATION }}, "tags": { "Created By": "Paul McCormack", "Service": "ARI Demo", "Cost Centre": "Test" }}'
      
      - name: checks-storage-deploy
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: validate
          name: validate-ari-storage
          location: ${{ env.AZURE_LOCATION }}
          scope: resourceGroup
          resource-group-name: ${{ env.AZURE_RESOURCE_GROUP }}
          template-file: ./bicep/storage.bicep
          parameters-file: ./bicep/storage.bicepparam
        
          