# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# This workflow will deploy Azure Resource Inventory using GitHub Actions and schedule a monthly run.

name: Deploy Azure Resource Inventory

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
    paths: 
      - 'bicep'
      - 'ps'
      - '.github/workflows/deploy.yml'
  
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  actions: read # Required if repo is private.
  contents: read # Required if repo is private.

env:
  AZURE_RESOURCE_GROUP: rg-uks-sandbox-ari-pmc
  AZURE_LOCATION: uksouth
  AUTOMATION_ACCOUNT_NAME: azinvautoaa-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Azure Login
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy Resource Group
        id: deployRg
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: deploy-ari-rg
          location: ${{ env.AZURE_LOCATION }}
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: ./bicep/rg.bicep
          parameters: '{"rgName": ${{ env.AZURE_RESOURCE_GROUP }}, "location": ${{ env.AZURE_LOCATION }}, "tags": { "Created By": "Paul McCormack", "Service": "ARI Demo", "Cost Centre": "Test" }}'
      
      - name: Deploy Storage Account
        id: deployStg
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: deploy-ari-storage
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ env.AZURE_RESOURCE_GROUP }}
          template-file: ./bicep/stg.bicep
          parameters-file: ./bicep/stg.bicepparam
      
      - name: Deploy ARI Runbook Script to Storage Account
        id: uploadScript
        uses: azure/powershell@v2
        with:
          inlineScript: |
            $saName = "${{ steps.deployStg.outputs.storageAccountName }}"
            $stgkey = Get-AzStorageAccountKey -ResourceGroupName ${{ env.AZURE_RESOURCE_GROUP }} -Name $saName | Where-Object {$_.KeyName -eq "key1"}
            $storageContext = New-AzStorageContext -StorageAccountName $saName -Protocol Https -StorageAccountKey $stgkey.Value
            Set-AzStorageBlobContent -File "ps/ari_runbook.ps1" -Container "scripts" -Context $storageContext -Force
            $startTime = Get-Date
            $endTime = $startTime.AddHours(1)
            $blobUri = New-AzStorageBlobSASToken -Container "scripts" -Blob "ari_runbook.ps1" -Context $storageContext -Permission "r" -StartTime $startTime -ExpiryTime $endTime -FullUri
            $fileHash = Get-FileHash -Path "ps/ari_runbook.ps1" -Algorithm SHA256
            $fileHashOutput = $fileHash.Hash
            "blob_uri=$blobUri" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            "file_hash=$fileHashOutput" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          azPSVersion: latest

      - name: Deploy Automation Account and Runbook
        id: deployRunbook
        #env:
        #  BLOB_URI: ${{ steps.uploadScript.outputs.blob_uri }}
        #  FILE_HASH: ${{ steps.uploadScript.outputs.file_hash }}
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: deploy-ari-automation
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ env.AZURE_RESOURCE_GROUP }}
          template-file: ./bicep/main.bicep
          #parameters: '{"automationAccountName": ${{ env.AUTOMATION_ACCOUNT_NAME }}, "existingStorageAccountName": ${{ steps.deployStg.outputs.storageAccountName }}, "runbookScriptUri": "${{ env.BLOB_URI }}", "runbookScriptHash": "${{ env.FILE_HASH }}"}'
          parameters: '{"automationAccountName": ${{ env.AUTOMATION_ACCOUNT_NAME }}, "existingStorageAccountName": ${{ steps.deployStg.outputs.storageAccountName }}, "runbookScriptUri": "${{ steps.uploadScript.outputs.blob_uri }}", "runbookScriptHash": "${{ steps.uploadScript.outputs.file_hash }}"}'
          

          